#include<stdio.h>
#include<string.h>
// you MANAGE A TRAVEL AGENCXY AND YOU HAVE N DRIVERS AND WANT YOUR N DRIVERS TO PUT THEIR FOLLOWING DETAILS
// 1.NAME
// 2.DRIVING LICENCE NUMBER
// 3.ROUTE
// 4.KMS
// YOU PROGRAMM SHOULD BE ABLE TO TAKE N AS INPUT AND YOUR DRIVER WILL STRAT INPUTTING THEIR DETAILS ONE BY ONE
int main()
{
   printf("%d\n",);
    return 0;
}